#!/bin/zsh
#
# Copyright 2021-Present Erik Gomez.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# If you change your agent file name, update the following line
launch_agent_plist_name='com.github.macadmins.Nudge.plist'

# Base paths
launch_agent_base_path='Library/LaunchAgents/'

# In Nudge 1.1.12.81501, a duplicate label caused corruption in the BTM database.
# Check for the touch file left by preinstall, and if present, remediate the corruption.
if [[ -f /private/var/tmp/nudge_remediate ]]; then
  echo "Upgrading from Nudge 1.1.12.81501 - proceeding with remediation."

  # Determine BTM plist path. On macOS 13.3 and lower, v4; higher and on to 14, v8.
  if [[ -f "/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v8.btm" ]]; then
    btm_plist_path="/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v8.btm"
    echo "Set BTM plist path to v8"
  elif [[ -f "/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v4.btm" ]]; then
    btm_plist_path="/private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v4.btm"
    echo "Set BTM plist path to v4"
  else
    echo "Error: unable to locate a BTM plist, no remediation occurred. Does this OS support BTM features?"
  fi

  line_count=0
  signing_re='.*"com.github.macadmins.Nudge".*T4SK8ZXCXG\)'
  dne_re=", Does Not Exist"
  signing_string='anchor apple generic and identifier \"com.github.macadmins.Nudge\" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = T4SK8ZXCXG)"'

  while True; do
    plist_entry=$(/usr/libexec/PlistBuddy -c "Print :\$objects:$line_count" $btm_plist_path 2>&1)
    if [[ "${plist_entry}" =~ $signing_re ]]; then
      # Remove the bad entry
      /usr/libexec/PlistBuddy -c "Delete :\$objects:$line_count" $btm_plist_path
      # Kickstart BTM to load in the modified DB
      /bin/launchctl kickstart -k system/com.apple.backgroundtaskmanagementd
      echo "Remediated BTM DB and kickstarted service."
      break

    elif [[ ${plist_entry} =~ ", Does Not Exist" ]] || [[ $line_count -gt 100000 ]]; then
      # Exit if we hit the end of the file or 100,000 lines (to avoid runaway)
      echo "Error: did not find signing data entry, or timed out at 100,000 lines processed."
      break
    else
      ((line_count++))
    fi
  done

  # Remove the touch file to not trigger remediation again.
  rm /private/var/tmp/nudge_remediate

else
  echo "No remediation needed for BTM issues."
fi

# Load agent if installing to a running system
if [[ $3 == "/" ]] ; then
  # Fail the install if the admin forgets to change their paths and they don't exist.
  if [ ! -e "$3/${launch_agent_base_path}${launch_agent_plist_name}" ]; then
    echo "LaunchAgent missing, exiting"
    exit 1
  fi

  # Current console user information
  console_user=$(/usr/bin/stat -f "%Su" /dev/console)
  console_user_uid=$(/usr/bin/id -u "$console_user")

  # Only enable the LaunchAgent if there is a user logged in, otherwise rely on built in LaunchAgent behavior
  if [[ -z "$console_user" ]]; then
    echo "Did not detect user"
  elif [[ "$console_user" == "loginwindow" ]]; then
    echo "Detected Loginwindow Environment"
  elif [[ "$console_user" == "_mbsetupuser" ]]; then
    echo "Detect SetupAssistant Environment"
  elif [[ "$console_user" == "root" ]]; then
    echo "Detect root as currently logged-in user"
  else
    # Unload the agent so it can be triggered on re-install
    /bin/launchctl asuser "${console_user_uid}" /bin/launchctl unload -w "$3${launch_agent_base_path}${launch_agent_plist_name}"
    # Kill Nudge just in case (say someone manually opens it and not launched via launchagent
    /usr/bin/killall Nudge
    # Load the launch agent
    /bin/launchctl asuser "${console_user_uid}" /bin/launchctl load -w "$3${launch_agent_base_path}${launch_agent_plist_name}"
  fi
fi
