#!/bin/zsh
#
# Copyright 2021-Present Erik Gomez.
#
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only run if on a running system
if [[ $3 == "/" ]] ; then
  # Current console user information
  console_user=$(/usr/bin/stat -f "%Su" /dev/console)

  # Only run if there is a user logged in, otherwise do nothing
  if [[ -z "$console_user" ]]; then
    echo "Did not detect user"
  elif [[ "$console_user" == "loginwindow" ]]; then
    echo "Detected Loginwindow Environment"
  elif [[ "$console_user" == "_mbsetupuser" ]]; then
    echo "Detect SetupAssistant Environment"
  elif [[ "$console_user" == "root" ]]; then
    echo "Detect root as currently logged-in user"
  else
    # Kill Nudge is running
    /usr/bin/pgrep -i Nudge | /usr/bin/xargs kill
  fi

  # In Nudge 1.1.12.81501, a duplicate label caused corruption in the BTM database.
  # Check if we are upgrading from 81501, and if so, touch a file to trigger postinstall
  # to remediate the corruption.
  if /usr/bin/grep -q -e ".*1.1.12.81501.*" /Applications/Utilities/Nudge.app/Contents/Info.plist; then
    echo "Nudge 1.1.12.81501 is installed - flagging for remediation."
    touch /private/var/tmp/nudge_remediate
  fi
fi
